######################## default configuration ####################
baseURL = "https://pslab-unibo.github.io"
title = "PS Lab "
theme = "pslab-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "research"
url = "#research"
weight = 1

[[Languages.en.menu.main]]
name = "team"
url = "#team"
weight = 2

[[Languages.en.menu.main]]
name = "blog"
url = "#blog"
weight = 3

[[Languages.en.menu.main]]
name = "info"
weight = 4
hasChildren = true

[[Languages.en.menu.main]]
parent = "info"
name = "thesis"
url = "#"
weight = 1

[[Languages.en.menu.main]]
parent = "info"
name = "intership"
url = "#"
weight = 2

################### French Navigation ########################
[[Languages.fr.menu.main]]
name = "sur"
url = "#about"
weight = 1

[[Languages.fr.menu.main]]
name = "un service"
url = "#services"
weight = 2

[[Languages.fr.menu.main]]
name = "portefeuille"
url = "#portfolio"
weight = 3

[[Languages.fr.menu.main]]
name = "équipe"
url = "#team"
weight = 4

[[Languages.fr.menu.main]]
name = "tarification"
url = "#pricing"
weight = 5

[[Languages.fr.menu.main]]
name = "blog"
url = "#blog"
weight = 6

[[Languages.fr.menu.main]]
name = "contact"
url = "#contact"
weight = 7

[[Languages.fr.menu.main]]
name = "themefisher"
url = "https://themefisher.com/"
weight = 8

############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Responsive Multipurpose Parallax Hugo Template"
author = "Themefisher"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

############################# social icons ##########################
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/pslab-unibo"

[[params.social]]
icon = "ti-cloud" # themify icon pack : https://themify.me/themify-icons
link = "https://apice.unibo.it/xwiki/bin/view/PSLab/"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"

################################ France Language ########################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
