name: Build and deploy
on:
  pull_request:
  push:
permissions:
  contents: write
jobs:
  success:
    runs-on: ubuntu-24.04
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive
          fetch-tags: 'true'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: 0.143.1
          extended: true
      - name: Build Hugo website
        run: hugo
      - name: Debug
        run: echo $GITHUB_REPOSITORY
      - name: Deploy staging
        if: github.event_name == 'push' && github.ref_name == 'master'
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          git-config-name: github-actions
          git-config-email: github-actions@github.com
          branch: gh-pages
          folder: public
      - name: Deploy official website
        if: github.event_name == 'push' && github.repository == 'pslab-unibo/web-frontend' && github.ref_name == 'master'
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          git-config-name: github-actions
          git-config-email: github-actions@github.com
          repository-name: pslab-unibo/pslab-unibo.github.io
          branch: master
          folder: public
